### ISSUE TITLE
Lint/EndAlignment warning in rubocop v0.53

### ISSUE THREAD

**Issue by aramvisser** [toshimaru/rubocop-rails#23]
Rubocop v0.53 moved `Lint/EndAlignment` to `Layout/EndAlignment` in bbatsov/rubocop@bbb10237fadc758ba2f15538f8d1ee64d4fe2710

Rubocop now gives the following warning when using rubocop-rails:

```
.../ruby/2.5.0/gems/rubocop-rails-1.2.2/config/rails.yml: Lint/EndAlignment has the wrong namespace - should be Layout
```

The fix is quite easy, simply change the `rails.yml` to use the Layout namespace and that removes the warning. However, that means older versions of rubocop will give a warning about the wrong namespace instead.

That seems fine to me, but I'm not sure if that is desired or not.

**Comment by toshimaru** [comment]
Good catch! 

Essentially, this project aims to catch up the official RoR RuboCop configuration, so I would say we don't need to change the configuration unless they(official RoR team) change the configuration.

If any concern, let me know.

**Comment by 0xifis** [comment]
I have sent a pull-request to update rails/rails rubocop version to 0.53. https://github.com/rails/rails/pull/32239

**Comment by toshimaru** [comment]
@vishthemenon Cool, let's re-open the issue and wait for getting the PR merged! :octocat:
